# Generated by Django 2.1.4 on 2019-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homewear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publ_date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
