# Generated by Django 2.1.4 on 2019-01-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homewear', '0002_product_publ_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publ_date',
        ),
    ]
